/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package problem2;

import java.util.ArrayList;
import java.util.Arrays;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;

/**
 *
 * @author mac
 */
public class checkoutWindow extends javax.swing.JFrame {

    private modifyWindow inputWindow2;
    private shoppingSystem inputWindow;
    private int orderNumber=0;
    ArrayList<customer> customers = new ArrayList<>();

//customer class = arraylist customer object = total
    /**
     * Creates new form checkoutWindow
     */
    public checkoutWindow() {
        initComponents();
    }

    public checkoutWindow(shoppingSystem inputWindow) {
        initComponents();

        this.inputWindow = inputWindow;
    }

    public checkoutWindow(modifyWindow inputWindow2) {
        initComponents();

        this.inputWindow2 = inputWindow2;
        //  modifyNameField.setText(name);
        //  modifyIdField.setText(id);
        //  modifyAgeField.setText(age);
    }

    private void groupButton() {

        ButtonGroup buttongroup1 = new ButtonGroup();

        buttongroup1.add(mrRadioButton);
        buttongroup1.add(mrsRadioButton);
        buttongroup1.add(missRadioButton);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        mrRadioButton = new javax.swing.JRadioButton();
        mrsRadioButton = new javax.swing.JRadioButton();
        missRadioButton = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        firstNameTextField = new javax.swing.JTextField();
        lastNameTextField = new javax.swing.JTextField();
        address1TextField = new javax.swing.JTextField();
        address2TextField = new javax.swing.JTextField();
        cityTextField = new javax.swing.JTextField();
        postcodeTextField = new javax.swing.JTextField();
        visaTextField = new javax.swing.JTextField();
        cancelCheckoutWindowButton = new javax.swing.JButton();
        submitCheckoutWindowButton = new javax.swing.JButton();
        stateSelectionComboBox = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buttonGroup1.add(mrRadioButton);
        mrRadioButton.setText("Mr.");

        buttonGroup1.add(mrsRadioButton);
        mrsRadioButton.setText("Mrs.");

        buttonGroup1.add(missRadioButton);
        missRadioButton.setText("Miss");

        jLabel1.setText("Title");

        jLabel2.setText("First Name");

        jLabel3.setText("Last Name:");

        jLabel4.setText("Address1:");

        jLabel5.setText("Address2:");

        jLabel6.setText("City:");

        jLabel7.setText("State:");

        jLabel8.setText("Postcode:");

        jLabel9.setText("Visa:");

        cancelCheckoutWindowButton.setText("Cancel");
        cancelCheckoutWindowButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelCheckoutWindowButtonActionPerformed(evt);
            }
        });

        submitCheckoutWindowButton.setText("Submit");
        submitCheckoutWindowButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitCheckoutWindowButtonActionPerformed(evt);
            }
        });

        stateSelectionComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "California", "Nevada", "Texas", "New Mexico" }));
        stateSelectionComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stateSelectionComboBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(postcodeTextField)
                            .addComponent(cityTextField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(address2TextField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(address1TextField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lastNameTextField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(26, 26, 26)
                                .addComponent(mrRadioButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(mrsRadioButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(missRadioButton))
                            .addComponent(firstNameTextField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(visaTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 271, Short.MAX_VALUE)
                            .addComponent(stateSelectionComboBox, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(cancelCheckoutWindowButton, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(submitCheckoutWindowButton, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mrRadioButton)
                    .addComponent(mrsRadioButton)
                    .addComponent(missRadioButton)
                    .addComponent(jLabel1))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(firstNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lastNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(address1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(address2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(stateSelectionComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(postcodeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(visaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelCheckoutWindowButton)
                    .addComponent(submitCheckoutWindowButton))
                .addGap(41, 41, 41))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelCheckoutWindowButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelCheckoutWindowButtonActionPerformed
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_cancelCheckoutWindowButtonActionPerformed

    public void reset() {
        firstNameTextField.setText(null);
        lastNameTextField.setText(null);
        address1TextField.setText(null);
        address2TextField.setText(null);
        cityTextField.setText(null);
        postcodeTextField.setText(null);
        visaTextField.setText(null);
    }
    
    private void submitCheckoutWindowButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitCheckoutWindowButtonActionPerformed
        //customer p1 = new customer(3, 3);

        if ((mrRadioButton.isSelected() == false && mrsRadioButton.isSelected() == false && missRadioButton.isSelected() == false)
                || firstNameTextField.getText().isEmpty() || lastNameTextField.getText().isEmpty() || address1TextField.getText().isEmpty()
                || address2TextField.getText().isEmpty() || cityTextField.getText().isEmpty() || postcodeTextField.getText().isEmpty()
                || visaTextField.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please Complate All Fields!", "Warning!", JOptionPane.WARNING_MESSAGE);
        } else {
            
customer c1 = new customer("Mr",firstNameTextField.getText(), lastNameTextField.getText(), address1TextField.getText(), address2TextField.getText(), cityTextField.getText(), stateSelectionComboBox.getSelectedItem().toString(), Integer.parseInt(postcodeTextField.getText()), Integer.parseInt(visaTextField.getText()) );
             
             
String state = stateSelectionComboBox.getSelectedItem().toString();


    //public customer(String title, String firstName, String lastName, String address1, String address2, String city, String state, int zipCode, int visa)

    JOptionPane.showMessageDialog(null, "Order Number " + orderNumber+ " *** Created.", "Order Confirmation", JOptionPane.INFORMATION_MESSAGE);
  
  customers.add(c1);
    //dispose();
    //System.out.println(c1);
   System.out.println(customers);
dispose();
}

// TODO add your handling code here:
    }//GEN-LAST:event_submitCheckoutWindowButtonActionPerformed

    private void stateSelectionComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stateSelectionComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stateSelectionComboBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                

}
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(checkoutWindow.class
.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        

} catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(checkoutWindow.class
.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        

} catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(checkoutWindow.class
.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        

} catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(checkoutWindow.class
.getName()).log(java.util.logging.Level.SEVERE, null, ex);
}
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new checkoutWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField address1TextField;
    private javax.swing.JTextField address2TextField;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton cancelCheckoutWindowButton;
    private javax.swing.JTextField cityTextField;
    private javax.swing.JTextField firstNameTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField lastNameTextField;
    private javax.swing.JRadioButton missRadioButton;
    private javax.swing.JRadioButton mrRadioButton;
    private javax.swing.JRadioButton mrsRadioButton;
    private javax.swing.JTextField postcodeTextField;
    private javax.swing.JComboBox<String> stateSelectionComboBox;
    private javax.swing.JButton submitCheckoutWindowButton;
    private javax.swing.JTextField visaTextField;
    // End of variables declaration//GEN-END:variables
}