/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package problem2;

import java.text.DecimalFormat;
import java.util.ArrayList;

/**
 *
 * @author mac
 */
public class shoppingSystem extends javax.swing.JFrame {
    final double beefPrice = 5.00;
    final double orangePrice = 2.00;
    final double carrotsPrice = 2.00;
    final double bananaPrice = 1.50;
    final double applePrice = 2.30;
    final double onionsPrice = 1.80;
    
    DecimalFormat formatter = new DecimalFormat("#0.00");

   
    public shoppingSystem() {
        initComponents();
    }

    public void reset() {
        applePoundsField.setText(null);
        onionsPoundsField.setText(null);
        bananaPoundsField.setText(null);
        carrotsPoundsField.setText(null);
        beefPoundsField.setText(null);
        orangePoundsField.setText(null);
    }

    public String orderTotal() {
        ArrayList<Double> subTotal = new ArrayList<>();
        double formatSum=0;
        double sum = 0;

        if (applePoundsField.getText().isEmpty()) {
            applePoundsField.setText("0");
        }

        if (beefPoundsField.getText().isEmpty()) {
            beefPoundsField.setText("0");
        }

        if (orangePoundsField.getText().isEmpty()) {
            orangePoundsField.setText("0");
        }

        if (onionsPoundsField.getText().isEmpty()) {
            onionsPoundsField.setText("0");
        }

        if (carrotsPoundsField.getText().isEmpty()) {
            carrotsPoundsField.setText("0");
        }

        if (bananaPoundsField.getText().isEmpty()) {
            bananaPoundsField.setText("0");
        }

        subTotal.add(applePrice * Double.parseDouble(applePoundsField.getText()));
        subTotal.add(beefPrice * Double.parseDouble(beefPoundsField.getText()));
        subTotal.add(orangePrice * Double.parseDouble(orangePoundsField.getText()));
        subTotal.add(onionsPrice * Double.parseDouble(onionsPoundsField.getText()));
        subTotal.add(carrotsPrice * Double.parseDouble(carrotsPoundsField.getText()));
        subTotal.add(bananaPrice * Double.parseDouble(bananaPoundsField.getText()));

        for (int i = 0; i < subTotal.size(); i++) {
            sum += subTotal.get(i);
        }
        return formatter.format(sum);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        beefPoundsField = new javax.swing.JTextField();
        orangePoundsField = new javax.swing.JTextField();
        carrotsPoundsField = new javax.swing.JTextField();
        bananaPoundsField = new javax.swing.JTextField();
        applePoundsField = new javax.swing.JTextField();
        onionsPoundsField = new javax.swing.JTextField();
        calculateTotalButton = new javax.swing.JButton();
        cancelShoppingButton = new javax.swing.JButton();
        searchShoppingButton = new javax.swing.JButton();
        resetShoppingButton = new javax.swing.JButton();
        checkoutShoppingButton = new javax.swing.JButton();
        totalLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Shopping System");

        jLabel1.setFont(new java.awt.Font("PT Sans Caption", 1, 16)); // NOI18N
        jLabel1.setText("Item");

        jLabel3.setFont(new java.awt.Font("PT Sans Caption", 1, 16)); // NOI18N
        jLabel3.setText("Apple");

        jLabel4.setFont(new java.awt.Font("PT Sans Caption", 1, 16)); // NOI18N
        jLabel4.setText("Onions");

        jLabel5.setFont(new java.awt.Font("PT Sans Caption", 1, 16)); // NOI18N
        jLabel5.setText("Carrots");

        jLabel6.setFont(new java.awt.Font("PT Sans Caption", 1, 16)); // NOI18N
        jLabel6.setText("Orange");

        jLabel7.setFont(new java.awt.Font("PT Sans Caption", 1, 16)); // NOI18N
        jLabel7.setText("Beef");

        jLabel8.setFont(new java.awt.Font("PT Sans Caption", 1, 16)); // NOI18N
        jLabel8.setText("Price Per Pound");

        jLabel9.setFont(new java.awt.Font("PT Sans Caption", 1, 16)); // NOI18N
        jLabel9.setText("Pounds");

        jLabel10.setFont(new java.awt.Font("PT Sans Caption", 1, 16)); // NOI18N
        jLabel10.setText("$5.00");

        jLabel11.setFont(new java.awt.Font("PT Sans Caption", 1, 16)); // NOI18N
        jLabel11.setText("$2.00");

        jLabel16.setFont(new java.awt.Font("PT Sans Caption", 1, 16)); // NOI18N
        jLabel16.setText("Banana");

        jLabel17.setFont(new java.awt.Font("PT Sans Caption", 1, 16)); // NOI18N
        jLabel17.setText("$2.00");

        jLabel18.setFont(new java.awt.Font("PT Sans Caption", 1, 16)); // NOI18N
        jLabel18.setText("$1.50");

        jLabel19.setFont(new java.awt.Font("PT Sans Caption", 1, 16)); // NOI18N
        jLabel19.setText("$2.30");

        jLabel20.setFont(new java.awt.Font("PT Sans Caption", 1, 16)); // NOI18N
        jLabel20.setText("$1.80");

        beefPoundsField.setFont(new java.awt.Font("Trajan Pro 3", 1, 13)); // NOI18N
        beefPoundsField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                beefPoundsFieldActionPerformed(evt);
            }
        });

        orangePoundsField.setFont(new java.awt.Font("Trajan Pro 3", 1, 13)); // NOI18N

        carrotsPoundsField.setFont(new java.awt.Font("Trajan Pro 3", 1, 13)); // NOI18N

        bananaPoundsField.setFont(new java.awt.Font("Trajan Pro 3", 1, 13)); // NOI18N
        bananaPoundsField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bananaPoundsFieldActionPerformed(evt);
            }
        });

        applePoundsField.setFont(new java.awt.Font("Trajan Pro 3", 1, 13)); // NOI18N
        applePoundsField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                applePoundsFieldActionPerformed(evt);
            }
        });

        onionsPoundsField.setFont(new java.awt.Font("Trajan Pro 3", 1, 13)); // NOI18N

        calculateTotalButton.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        calculateTotalButton.setText("Calculate Total");
        calculateTotalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculateTotalButtonActionPerformed(evt);
            }
        });

        cancelShoppingButton.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        cancelShoppingButton.setText("Cancel");
        cancelShoppingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelShoppingButtonActionPerformed(evt);
            }
        });

        searchShoppingButton.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        searchShoppingButton.setText("Search");
        searchShoppingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchShoppingButtonActionPerformed(evt);
            }
        });

        resetShoppingButton.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        resetShoppingButton.setText("Reset");
        resetShoppingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetShoppingButtonActionPerformed(evt);
            }
        });

        checkoutShoppingButton.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        checkoutShoppingButton.setText("Checkout");
        checkoutShoppingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkoutShoppingButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cancelShoppingButton, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchShoppingButton, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(resetShoppingButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(checkoutShoppingButton, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(calculateTotalButton, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel16))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(100, 100, 100)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel11)
                                            .addComponent(jLabel10)
                                            .addComponent(jLabel17)
                                            .addComponent(jLabel18)
                                            .addComponent(jLabel19)
                                            .addComponent(jLabel20)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(67, 67, 67)
                                        .addComponent(jLabel8)))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(91, 91, 91)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addGap(0, 60, Short.MAX_VALUE))
                                    .addComponent(orangePoundsField)
                                    .addComponent(carrotsPoundsField)
                                    .addComponent(bananaPoundsField)
                                    .addComponent(applePoundsField)
                                    .addComponent(onionsPoundsField)
                                    .addComponent(beefPoundsField))
                                .addGap(26, 26, 26))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(totalLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel3, jLabel4, jLabel5, jLabel6, jLabel7});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel10, jLabel11, jLabel17, jLabel18, jLabel19, jLabel20});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cancelShoppingButton, checkoutShoppingButton, resetShoppingButton, searchShoppingButton});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel10)
                    .addComponent(beefPoundsField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel11)
                    .addComponent(orangePoundsField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel17)
                        .addComponent(carrotsPoundsField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel18)
                        .addComponent(bananaPoundsField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel19)
                        .addComponent(applePoundsField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel20)
                        .addComponent(onionsPoundsField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(totalLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(calculateTotalButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelShoppingButton)
                    .addComponent(searchShoppingButton)
                    .addComponent(resetShoppingButton)
                    .addComponent(checkoutShoppingButton))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel3, jLabel4, jLabel5, jLabel6, jLabel7});

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bananaPoundsFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bananaPoundsFieldActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_bananaPoundsFieldActionPerformed

    private void searchShoppingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchShoppingButtonActionPerformed
        modifyWindow window2 = new modifyWindow(this);
        window2.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_searchShoppingButtonActionPerformed

    private void checkoutShoppingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkoutShoppingButtonActionPerformed
        checkoutWindow window2 = new checkoutWindow(this);
        window2.setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_checkoutShoppingButtonActionPerformed

    private void cancelShoppingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelShoppingButtonActionPerformed
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_cancelShoppingButtonActionPerformed

    private void beefPoundsFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_beefPoundsFieldActionPerformed

    }//GEN-LAST:event_beefPoundsFieldActionPerformed

    private void resetShoppingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetShoppingButtonActionPerformed
        reset();        // TODO add your handling code here:
    }//GEN-LAST:event_resetShoppingButtonActionPerformed

    private void applePoundsFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_applePoundsFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_applePoundsFieldActionPerformed

    private void calculateTotalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculateTotalButtonActionPerformed
        totalLabel.setText("$" + orderTotal());
    }//GEN-LAST:event_calculateTotalButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(shoppingSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(shoppingSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(shoppingSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(shoppingSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new shoppingSystem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField applePoundsField;
    private javax.swing.JTextField bananaPoundsField;
    private javax.swing.JTextField beefPoundsField;
    private javax.swing.JButton calculateTotalButton;
    private javax.swing.JButton cancelShoppingButton;
    private javax.swing.JTextField carrotsPoundsField;
    private javax.swing.JButton checkoutShoppingButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField onionsPoundsField;
    private javax.swing.JTextField orangePoundsField;
    private javax.swing.JButton resetShoppingButton;
    private javax.swing.JButton searchShoppingButton;
    private javax.swing.JLabel totalLabel;
    // End of variables declaration//GEN-END:variables
}
